//@ts-nocheck
export const vocabularyArray = {
  Adjective: [
    {
      word: 'Bra',
      meaning: 'Great',
    },
    { word: 'gift', meaning: 'married' },
    { word: 'singel', meaning: 'single' },
    { word: 'trött', meaning: 'tired' },
    { word: 'glad', meaning: 'happy' },
    { word: 'sjuk', meaning: 'sick' },
  ],
  Adverb: [
    {
      word: 'Där',
      meaning: 'there',
    },
    {
      word: 'Här',
      meaning: 'here',
    },
    {
      word: 'Inte',
      meaning: 'not',
    },
  ],
  Conjunction: [
    {
      word: 'Eller',
      meaning: 'Or',
    },
    {
      word: 'Men',
      meaning: 'But',
    },
    {
      word: 'Och',
      meaning: 'And',
    },
  ],
  Noun: [
    {
      word: 'pensionär',
      meaning: 'retired person',
    },
  ],
  Phrase: [
    {
      word: 'Den där',
      meaning: 'that (common gender)',
    },
    {
      word: 'Den här',
      meaning: 'this (common gender)',
    },
    {
      word: 'Det där',
      meaning: 'that (neuter gender)',
    },
    {
      word: 'Det här',
      meaning: 'this (neuter gender)',
    },
    {
      word: 'Hej',
      meaning: 'Hi / Hello',
    },
    {
      word: 'Jag arbetar inte.',
      meaning: 'I’m not working.',
    },
    {
      word: 'Jag heter ...',
      meaning: 'My name is ...',
    },
    {
      word: 'Jag jobbar inte.',
      meaning: 'I’m not working.',
    },
    {
      word: 'Jag kommer från ...',
      meaning: 'I come from ...',
    },
    {
      word: 'Jag pluggar.',
      meaning: 'I study.',
    },
    {
      word: 'Jag talar svenska och engelska.',
      meaning: 'I speak Swedish and English.',
    },
    {
      word: 'Jobbar du?',
      meaning: 'Do you work?',
    },
    {
      word: 'Lycka till',
      meaning: 'good luck',
    },
    {
      word: 'Nähä',
      meaning: 'oh, I don not know',
    },
    {
      word: 'Tack',
      meaning: 'Thank you',
    },
    {
      word: 'Vad gör du?',
      meaning: 'What do you do?',
    },
    {
      word: 'Vad heter du?',
      meaning: 'What is your name?',
    },
    {
      word: 'Vad studerar du?',
      meaning: 'What are you studying?',
    },
    {
      word: 'Vad talar du för språk?',
      meaning: 'What language do you speak?',
    },
    {
      word: 'Varifrån kommer du?',
      meaning: 'Where are you from?',
    },
    {
      word: 'hej då!',
      meaning: 'bye',
    },

    { word: 'Jag är singel.', meaning: 'I am single.' },
    { word: 'Jag har två barn.', meaning: 'I have two children.' },
    { word: 'Min man är från Indien.', meaning: 'My husband is from India.' },
  ],

  Noun: [
    { word: 'Advokat', meaning: 'lawyer' },
    { word: 'Läkare', meaning: 'doctor' },
    { word: 'Ingenjör', meaning: 'engineer' },
    { word: 'Lärare', meaning: 'teacher' },
    { word: 'Buss', meaning: 'bus' },
    { word: 'Busschaufför', meaning: 'bus driver' },
    { word: 'Fotograf', meaning: 'photographer' },
    { word: 'Servitör', meaning: 'waiter' },
    { word: 'kock', meaning: 'cook' },
    { word: 'Sjuksköterska', meaning: 'nurse' },
    { word: 'Tandläkare', meaning: 'dentist' },
    { word: 'Webbdesigner', meaning: 'web designer' },
    { word: 'Frisör', meaning: 'hairdresser' },
    { word: 'Apelsin', meaning: 'Orange' },
    { word: 'Apa', meaning: 'Monkey' },
    { word: 'Ananas', meaning: 'Pineapple' },
    { word: 'Barn', meaning: 'Child' },
    { word: 'Bil', meaning: 'Car' },
    { word: 'Banan', meaning: 'Banana' },
    { word: 'Bröd', meaning: 'Bread' },
    { word: 'Citron', meaning: 'Lemon' },
    { word: 'Välkommen', meaning: 'Welcome' },
    { word: 'Vin', meaning: 'Wine' },
    { word: 'Vatten', meaning: 'Water' },
    { word: 'Cykel', meaning: 'Bicycle' },
    { word: 'Dator', meaning: 'Computer' },
    { word: 'Delfin', meaning: 'Dolphin' },
    { word: 'Elefant', meaning: 'Elephant' },
    { word: 'Eld', meaning: 'Fire' },
    { word: 'Flicka', meaning: 'Girl' },
    { word: 'Flygplan', meaning: 'Plane' },
    { word: 'Fotboll', meaning: 'Football' },
    { word: 'Glass', meaning: 'Ice cream' },
    { word: 'Gurka', meaning: 'Cucumber' },
    { word: 'Hund', meaning: 'Dog' },
    { word: 'Häst', meaning: 'Horse' },
    { word: 'Is', meaning: 'Ice' },
    { word: 'Jordgubbe', meaning: 'Strawberry' },
    { word: 'Katt', meaning: 'Cat' },
    { word: 'Klocka', meaning: 'Clock' },
    { word: 'Kurs', meaning: 'Classroom' },
    { word: 'kul', meaning: 'cool' },
    { word: 'Lejon', meaning: 'Lion' },
    { word: 'Lampa', meaning: 'Lamp' },
    { word: 'Mjölk', meaning: 'Milk' },
    { word: 'Mat', meaning: 'Food' },
    { word: 'Nalle', meaning: 'Teddy bear' },
    { word: 'ja', meaning: 'Yes' },
    { word: 'Nej', meaning: 'No' },
    { word: 'Nyckel', meaning: 'Key' },
    { word: 'Ost', meaning: 'Cheese' },
    { word: 'Olja', meaning: 'Oil' },
    { word: 'Pojke', meaning: 'Boy' },
    { word: 'Penna', meaning: 'Pen' },
    { word: 'Papper', meaning: 'Paper' },
    { word: 'Qvint', meaning: 'Fifth (music)' },
    { word: 'Ris', meaning: 'Rice' },
    { word: 'Räv', meaning: 'Fox' },
    { word: 'Stol', meaning: 'Chair' },
    { word: 'Jaha', meaning: 'I see' },
    { word: 'Såklart', meaning: 'of course' },
    { word: 'Sol', meaning: 'Sun' },
    { word: 'Tomat', meaning: 'Tomato' },
    { word: 'Teve', meaning: 'Television' },
    { word: 'Te', meaning: 'Tea' },
    { word: 'Tåg', meaning: 'Train' },
    { word: 'Vän', meaning: 'Friend' },
    { word: 'Vindruva', meaning: 'Grapes' },
    { word: 'Vägg', meaning: 'Wall' },
    { word: 'Xylofon', meaning: 'Xylophone' },
    { word: 'Yoghurt', meaning: 'Yogurt' },
    { word: 'Yng', meaning: 'Young' },
    { word: 'Zebra', meaning: 'Zebra' },
    { word: 'År', meaning: 'Year' },
    { word: 'Äpple', meaning: 'Apple' },
    { word: 'Öga', meaning: 'Eye' },
    { word: 'Öl', meaning: 'Beer' },
    { word: 'Sida', meaning: 'Page' },
    { word: 'Bok', meaning: 'Book' },
    { word: 'Kapitel', meaning: 'Chapter' },
    { word: 'Svar', meaning: 'Answer' },
    { word: 'Fråga', meaning: 'Question' },
    { word: 'sambo', meaning: 'partner (living together)' },
    { word: 'skild', meaning: 'divorced' },
    { word: 'separerad', meaning: 'separated' },
    { word: 'pojkvän', meaning: 'boyfriend' },
    { word: 'flickvän', meaning: 'girlfriend' },
    { word: 'man', meaning: 'husband' },
    { word: 'fru', meaning: 'wife' },
    { word: 'son', meaning: 'son' },
    { word: 'dotter', meaning: 'daughter' },
    { word: 'barn', meaning: 'child' },
    { word: 'bonusbarn', meaning: 'stepchild' },
    { word: 'föräldrar', meaning: 'parents' },
    { word: 'mamma', meaning: 'mom' },
    { word: 'pappa', meaning: 'dad' },
    { word: 'syskon', meaning: 'siblings' },
    { word: 'bror', meaning: 'brother' },
    { word: 'syster', meaning: 'sister' },
    { word: 'student', meaning: 'student' },
    { word: 'från Sverige', meaning: 'from Sweden' },
  ],
  Preposition: [
    {
      word: 'Från',
      meaning: 'From',
    },
  ],
  Pronoun: [
    { word: 'Jag', meaning: 'I' },
    { word: 'Du', meaning: 'You' },
    { word: 'Han', meaning: 'He' },
    { word: 'Hon', meaning: 'She' },
    { word: 'Vi', meaning: 'We' },
    { word: 'Ni', meaning: 'You (plural)' },
    { word: 'De', meaning: 'They' },
  ],
  Question: [
    { word: 'Vad', meaning: 'What' },
    { word: 'Varifrån', meaning: 'Where from' },
  ],
  Verb: [
    { word: 'Jobbar', meaning: 'work' },
    { word: 'Arbetar', meaning: 'work' },
    { word: 'Talar', meaning: 'Speak' },
    { word: 'Kommer', meaning: 'Come' },
    { word: 'söker', meaning: 'looking for' },
    { word: 'Lära', meaning: 'Learn' },
    { word: 'Studera', meaning: 'Study' },
    { word: 'Börja', meaning: 'Begin' },
    { word: 'Sluta', meaning: 'End' },
    { word: 'Lyssna', meaning: 'Listen' },
    { word: 'Heter', meaning: 'Am called' },
    { word: 'Bor', meaning: 'lives' },
  ],
};
