//@ts-nocheck
export const vocabulary = JSON.parse(localStorage.getItem('vocabulary')) || [
  { word: 'Vad heter du?', meaning: 'What is your name?', category: 'Phrase' },
  { word: 'Jag heter ...', meaning: 'My name is ...', category: 'Phrase' },
  {
    word: 'Varifrån kommer du?',
    meaning: 'Where are you from?',
    category: 'Phrase',
  },
  {
    word: 'Jag kommer från ...',
    meaning: 'I come from ...',
    category: 'Phrase',
  },
  {
    word: 'Vad talar du för språk?',
    meaning: 'What language do you speak?',
    category: 'Phrase',
  },
  {
    word: 'Jag talar svenska och engelska.',
    meaning: 'I speak Swedish and English.',
    category: 'Phrase',
  },
  { word: 'Bra', meaning: 'Great', category: 'Adjective' },
  { word: 'Jag jobbar inte.', meaning: 'I’m not working.', category: 'Phrase' },
  {
    word: 'Jag arbetar inte.',
    meaning: 'I’m not working.',
    category: 'Phrase',
  },
  { word: 'inte', meaning: 'not', category: 'Adverb' },
  { word: 'jobbar', meaning: 'work', category: 'Verb' },
  { word: 'arbetar', meaning: 'work', category: 'Verb' },
  { word: 'söker', meaning: 'looking for', category: 'Verb' },
  { word: 'pensionär', meaning: 'retired person', category: 'Noun' },
  { word: 'Jobbar du?', meaning: 'Do you work?', category: 'Phrase' },
  { word: 'Jag pluggar.', meaning: 'I study.', category: 'Phrase' },
  { word: 'Vad gör du?', meaning: 'What do you do?', category: 'Phrase' },
  {
    word: 'Vad studerar du?',
    meaning: 'What are you studying?',
    category: 'Phrase',
  },
  { word: 'här', meaning: 'here', category: 'Adverb' },
  { word: 'där', meaning: 'there', category: 'Adverb' },
  { word: 'den här', meaning: 'this (common gender)', category: 'Phrase' },
  { word: 'det här', meaning: 'this (neuter gender)', category: 'Phrase' },
  { word: 'den där', meaning: 'that (common gender)', category: 'Phrase' },
  { word: 'det där', meaning: 'that (neuter gender)', category: 'Phrase' },

  { word: 'advokat', meaning: 'lawyer', category: 'Noun' },
  { word: 'läkare', meaning: 'doctor', category: 'Noun' },
  { word: 'ingenjör', meaning: 'engineer', category: 'Noun' },
  { word: 'lärare', meaning: 'teacher', category: 'Noun' },
  { word: 'busschaufför', meaning: 'bus driver', category: 'Noun' },
  { word: 'fotograf', meaning: 'photographer', category: 'Noun' },
  { word: 'servitör', meaning: 'waiter', category: 'Noun' },
  { word: 'kock', meaning: 'cook', category: 'Noun' },
  { word: 'sjuksköterska', meaning: 'nurse', category: 'Noun' },
  { word: 'tandläkare', meaning: 'dentist', category: 'Noun' },
  { word: 'webbdesigner', meaning: 'web designer', category: 'Noun' },
  { word: 'frisör', meaning: 'hairdresser', category: 'Noun' },
  { word: 'Apelsin', meaning: 'Orange', category: 'Noun' },
  { word: 'Apa', meaning: 'Monkey', category: 'Noun' },
  { word: 'Ananas', meaning: 'Pineapple', category: 'Noun' },
  { word: 'Barn', meaning: 'Child', category: 'Noun' },
  { word: 'Bil', meaning: 'Car', category: 'Noun' },
  { word: 'Bra', meaning: 'great', category: 'Noun' },
  { word: 'Banan', meaning: 'Banana', category: 'Noun' },
  { word: 'Citron', meaning: 'Lemon', category: 'Noun' },
  { word: 'Cykel', meaning: 'Bicycle', category: 'Noun' },
  { word: 'Dator', meaning: 'Computer', category: 'Noun' },
  { word: 'Delfin', meaning: 'Dolphin', category: 'Noun' },
  { word: 'Elefant', meaning: 'Elephant', category: 'Noun' },
  { word: 'Eld', meaning: 'Fire', category: 'Noun' },
  { word: 'Flicka', meaning: 'Girl', category: 'Noun' },
  { word: 'Flygplan', meaning: 'Plane', category: 'Noun' },
  { word: 'Fotboll', meaning: 'Football', category: 'Noun' },
  { word: 'Glass', meaning: 'Ice cream', category: 'Noun' },
  { word: 'Gurka', meaning: 'Cucumber', category: 'Noun' },
  { word: 'Hund', meaning: 'Dog', category: 'Noun' },
  { word: 'Häst', meaning: 'Horse', category: 'Noun' },
  { word: 'Is', meaning: 'Ice', category: 'Noun' },
  { word: 'Jordgubbe', meaning: 'Strawberry', category: 'Noun' },
  { word: 'Katt', meaning: 'Cat', category: 'Noun' },
  { word: 'Klocka', meaning: 'Clock', category: 'Noun' },
  { word: 'Kurs', meaning: 'Classroom', category: 'Noun' },
  { word: 'Lejon', meaning: 'Lion', category: 'Noun' },
  { word: 'Lampa', meaning: 'Lamp', category: 'Noun' },
  { word: 'Mjölk', meaning: 'Milk', category: 'Noun' },
  { word: 'Mat', meaning: 'Food', category: 'Noun' },
  { word: 'Nalle', meaning: 'Teddy bear', category: 'Noun' },
  { word: 'Nej', meaning: 'No', category: 'Noun' },
  { word: 'Nyckel', meaning: 'Key', category: 'Noun' },
  { word: 'Ost', meaning: 'Cheese', category: 'Noun' },
  { word: 'Och', meaning: 'And', category: 'Conjunction' },
  { word: 'Olja', meaning: 'Oil', category: 'Noun' },
  { word: 'Pojke', meaning: 'Boy', category: 'Noun' },
  { word: 'Penna', meaning: 'Pen', category: 'Noun' },
  { word: 'Papper', meaning: 'Paper', category: 'Noun' },
  { word: 'Qvint', meaning: 'Fifth (music)', category: 'Noun' },
  { word: 'Ris', meaning: 'Rice', category: 'Noun' },
  { word: 'Räv', meaning: 'Fox', category: 'Noun' },
  { word: 'Stol', meaning: 'Chair', category: 'Noun' },
  { word: 'Jaha', meaning: 'I see', category: 'Noun' },
  { word: 'Såklart', meaning: 'of course', category: 'Noun' },
  { word: 'Sol', meaning: 'Sun', category: 'Noun' },
  { word: 'Tack', meaning: 'Thank you', category: 'Phrase' },
  { word: 'Tomat', meaning: 'Tomato', category: 'Noun' },
  { word: 'Teve', meaning: 'Television', category: 'Noun' },
  { word: 'Tåg', meaning: 'Train', category: 'Noun' },
  { word: 'Underbar', meaning: 'Wonderful', category: 'Adjective' },
  { word: 'Vän', meaning: 'Friend', category: 'Noun' },
  { word: 'Vindruva', meaning: 'Grapes', category: 'Noun' },
  { word: 'Vägg', meaning: 'Wall', category: 'Noun' },
  { word: 'Xylofon', meaning: 'Xylophone', category: 'Noun' },
  { word: 'Yoghurt', meaning: 'Yogurt', category: 'Noun' },
  { word: 'Zebra', meaning: 'Zebra', category: 'Noun' },
  { word: 'År', meaning: 'Year', category: 'Noun' },
  { word: 'Äpple', meaning: 'Apple', category: 'Noun' },
  { word: 'Öga', meaning: 'Eye', category: 'Noun' },
  { word: 'Sida', meaning: 'Page', category: 'Noun' },
  { word: 'Bok', meaning: 'Book', category: 'Noun' },
  { word: 'Kapitel', meaning: 'Chapter', category: 'Noun' },
  { word: 'Svar', meaning: 'Answer', category: 'Noun' },
  { word: 'Fråga', meaning: 'Question', category: 'Noun' },
  { word: 'Lära', meaning: 'Learn', category: 'Verb' },
  { word: 'Studera', meaning: 'Study', category: 'Verb' },
  { word: 'Börja', meaning: 'Begin', category: 'Verb' },
  { word: 'Sluta', meaning: 'End', category: 'Verb' },
  { word: 'Lyssna', meaning: 'Listen', category: 'Verb' },
  { word: 'Hej', meaning: 'Hi / Hello', category: 'Phrase' },
  { word: 'Jag', meaning: 'I', category: 'Pronoun' },
  { word: 'Du', meaning: 'You', category: 'Pronoun' },
  { word: 'Heter', meaning: 'Am called', category: 'Verb' },
  { word: 'Kommer', meaning: 'Come', category: 'Verb' },
  { word: 'Från', meaning: 'From', category: 'Preposition' },
  { word: 'Varifrån', meaning: 'Where from', category: 'Question' },
  { word: 'Talar', meaning: 'Speak', category: 'Verb' },
  { word: 'Vad', meaning: 'What', category: 'Question' },
  { word: 'Hon', meaning: 'She', category: 'Pronoun' },
  { word: 'Han', meaning: 'He', category: 'Pronoun' },
  { word: 'Vi', meaning: 'We', category: 'Pronoun' },
  { word: 'Ni', meaning: 'You (plural)', category: 'Pronoun' },
  { word: 'De', meaning: 'They', category: 'Pronoun' },
  { word: 'Apelsin', meaning: 'Orange', category: 'Noun' },
  { word: 'Hund', meaning: 'Dog', category: 'Noun' },
  { word: 'Katt', meaning: 'Cat', category: 'Noun' },
  { word: 'Underbar', meaning: 'Wonderful', category: 'Adjective' },
  { word: 'Tack', meaning: 'Thank you', category: 'Phrase' },
  { word: 'Jaha', meaning: 'I see', category: 'Phrase' },
  { word: 'Nähä', meaning: 'oh really', category: 'Phrase' },
  { word: 'Lycka till', meaning: 'good luck', category: 'Phrase' },
  { word: 'Och', meaning: 'And', category: 'Conjunction' },
  { word: 'Foton', meaning: 'Photos', category: 'Noun' },
  { word: 'Ord', meaning: 'Word', category: 'Noun' },
  { word: 'Eller', meaning: 'Or', category: 'Conjunction' },
];
